MAP_SIZE = 128
VIEW_SIZE = 21
CELL_SIZE = 24
SIDE_PANEL_WIDTH = 330
FPS = 60

PLAYER_BASE_SPEED = 4.0
PLAYER_STEP_SCORE = 1.5
DASH_COOLDOWN_SECONDS = 80.0
DASH_DISTANCE = 8

MONSTER_BASE_SPEED = 4.0
MONSTER_SPAWN_MIN_DISTANCE = 4
MONSTER_SPAWN_MAX_DISTANCE = 8
MONSTER2_SPAWN_TIME_SECONDS = 100.0
MONSTER_SPEEDUP_TIME_SECONDS = 200.0
MONSTER_SPEEDUP_MULTIPLIER = 2.0

CHEST_MIN_COUNT = 8
CHEST_MAX_COUNT = 10
CHEST_SCORE = 100

BUFF_COUNT = 2
BUFF_RESPAWN_SECONDS = 80.0
BUFF_DURATION_SECONDS = 12.0
BUFF_SPEED_MULTIPLIER = 2.0

WIN_SURVIVAL_SECONDS = 400.0
RECORD_INTERVAL_SECONDS = 1.0

FALLBACK_OBSTACLE_DENSITY = 0.22
